name: todo_list
description: Todo-list productive application

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.4 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  intl: ^0.18.0
  cupertino_icons: ^1.0.2
  firebase_database: ^10.1.1
  provider: ^6.0.5
  syncfusion_flutter_calendar: ^22.1.39
  syncfusion_localizations: ^22.1.39
  firebase_core:
  firebase_auth: ^4.9.0 
  firebase_storage: ^11.2.6
  cloud_firestore:
  font_awesome_flutter: ^10.4.0
  shared_preferences: ^2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
